### ISSUE TITLE
gbGetUser() only works in HTML5

### ISSUE THREAD

**Issue by thorstenvonberswordt** [goodbarber/gbjstk#2]
The gbGetUser() Function only works in HTML5 not native apps. Should not be part of released JS toolkit, or commented with this shortcoming since developers usually will want tii target all three GB platforms (HTML5 IOS Android)

**Comment by Rayjax** [comment]
Actually gbGetUser works on android as well, but will return a string instead of an object. Not all fields will be available and not in the same format. Looking forward for an update to this

**Comment by thorstenvonberswordt** [comment]
Would be nice if behavior is same in android, html5 and ios. Furthermore self defined fields should be carried (as the html5 version does) since that opens up a whole new world of possibilities one can accomplish using the GoodBarber stack

**Comment by goodbarber** [comment]
Hi,

we made some modifications. All platforms should have the same behaviour.

Best,
Mathieu 
GoodBarber Team

**Comment by Cm-8** [comment]
Hi to all,
I have same issue.
gbGetUser() Function only works in HTML5 not native apps.
https://github.com/goodbarber/plugin_demo/issues/1
