### ISSUE TITLE
problems with getpreference and setpreference

### ISSUE THREAD

**Issue by fachamix** [goodbarber/gbjstk#3]
Hello:

I am having troubles trying to use the functions gbSetPreference and gbGetPreference.

I have been trying to use them, but no luck so far.

Could anyone guide me with an example of them ?

**Comment by matteuf** [comment]
Hi,

I'll make an update of the plugin_demo, with a demo of a using the methods gbSetPreference & gbGetPreference.

Mathieu
GoodBarber team

**Comment by matteuf** [comment]
Hi,

here's a new version of the demo plugin containing an implementation of gbSetPreference & gbGetPreference methods.

Don't hesitate if you have feedbacks or questions on it.

Mathieu 
GoodBarber team

**Comment by juancarmo** [comment]
The plugin demo works perfectly, I opened another issue for something related, this should be closed.

**Comment by ptykamikaze** [comment]
Hello sorry for asking. Where are these examples located?
