### ISSUE TITLE
Custom Main Menu - get/set preference problem

### ISSUE THREAD

**Issue by juancarmo** [goodbarber/gbjstk#4]
Although the demonstration plugin code works perfectly (I mean the get/set preference methods), .... I cannot use them in the main menu I built from scratch ... is it possible to use the get/set Preference methods in the main menu?

**Comment by goodbarber** [comment]
Hi,

as for now all Plugins methods are only available in Plugin section. Not in Scratch menu & Scratch Multi-level sections.

Best,
Mathieu 
GoodBarber Team
