### ISSUE TITLE
Custom Main Menu - images not loading

### ISSUE THREAD

**Issue by juancarmo** [goodbarber/gbjstk#5]
In the main menu (main section), and other menues (other sections), some images are not loading right .... and I tried to reload them using javascript with the following code but I had no luck:

in the body section:

```
		<script type="text/javascript">

			$(document).ready(function(){
                               
				$('img').each(function(){

					if (!$(this).complete) {
						d = new Date();
						$(this).attr("src", $(this).attr("src") +"?"+d.getTime());	
					}
				});

			});
		</script>

```

Here I attach some images showing the problem per se....

![screenshot_2016-12-23-23-31-50](https://cloud.githubusercontent.com/assets/25756860/25391077/c0abf486-29ab-11e7-97f5-17afbc979569.png)
![screenshot_2016-12-23-23-31-59](https://cloud.githubusercontent.com/assets/25756860/25391076/c0ab2628-29ab-11e7-8f25-0835435746c8.png)
![screenshot_2016-12-23-23-32-08](https://cloud.githubusercontent.com/assets/25756860/25391078/c0ae9808-29ab-11e7-8b8c-03e07110a4ea.png)

Hope someone can guide me through this issue

**Comment by goodbarber** [comment]
Hi,

can you contact the support about this issue. Tell them to forward the ticket to me (Mathieu). So I can take a look on the problem.

Best,
Mathieu
GoodBarber Team
