### ISSUE TITLE
gbLog ios condition always evaluates to true

### ISSUE THREAD

**Issue by egeis** [goodbarber/gbjstk#6]
I inserted several gbLogs, replacing console logs I had hard coded while testing an issue occurring on mobile / native version of my plugin when I saw that the alert for IOS occurring on android.  The console.log is unreachable as the conditional evaluates true on all due to logical-or being hard set to true.

X AND Y OR Z = (true|false) AND (true|false) OR (true) > simplified to > (true|false) OR (true) == true as OR only return false if both operands are false, as the second operand is always true then console.log becomes unreachable.

`function gbLogs( log )
{
	alert(gbUserInfo.platform);
	if (gbUserInfo && gbUserInfo.platform == 'ios' || true) 
	{
		alert("c'est bon ios");
		gbGetRequest ( "goodbarber://logs=" + encodeURIComponent(log));
	}
	else 
	{
		console.log(log);
	}
}`

I made the correction on my own and removed the additional alerts as they were slowing down my testing.  Would probably be easier to run a switch...case for each platform to handle error logging. If android, windows mobile, etc. have different logging methods for errors.

`function gbLogs( log )
{
	if ( gbUserInfo.platform === 'ios' ) 
	{
		gbGetRequest ( "goodbarber://logs=" + encodeURIComponent(log));
	}
	else
	{
		console.log(log);
	}
}`

**Comment by goodbarber** [comment]
Oops, we forgot to remove some debug stuff. We'll make an update to fix it.

Thank you for the feedback !
