### ISSUE TITLE
How to request goodbarber://getuser over HTTPS

### ISSUE THREAD

**Issue by ptykamikaze** [goodbarber/gbjstk#7]
I'm trying to get the user email using the goodbarber javascript toolkit but I can't find a way to do it. I have tried google and looking for some sort of documentation but I couldn't find something useful. Please help!!.

**Comment by ptykamikaze** [comment]
I could managed to use propertly the gbGetUser function but now I have another problem get getting user information over HTTPS: "......was loaded over HTTPS, but requested an insecure resource 'goodbarber://getuser'. This content should also be served over HTTPS.".... so it works fine in my test schema which is HTTP, but when I moved to production, which is in HTTPS, I'm getting that error and in the APP nothing is being loaded. Please help!

**Comment by ptykamikaze** [comment]
thanks for the great help

**Comment by Guillaume-Cecchini** [comment]
Hi, @ptykamikaze, @goodbarber ,
I'm working on an pwa make with goodbarber but i can't manage the gbGetUser. 
I'm trying to retrieve the userName and other informations of the user logged into the app. 
Do you have any idea how to do that ?
Honestly with the online help and the support I'm going nowhere (probably my bad).
