### ISSUE TITLE
gbGoToSection(id) not working in "My Goodbarber"

### ISSUE THREAD

**Issue by jicao** [goodbarber/gbjstk#8]
Hello,

The function gbGoToSection ( id ) is not working in the My GB APP native mode.
This only works on browser html5.
(It still work with GBJSTKv3.js)

Thanks

**Comment by matteuf** [comment]
Hi !

the MyGoodBarber app is not available anymore on the store. If you also have this problem on your app built, contact the support from your backoffice.

Mathieu
GoodBarber
